version: '3.8'

services:
  flask-app:
    build: ./app  # Path ke Dockerfile Flask Anda
    container_name: flask-todo-app-container
    restart: always
    ports:
      - "5000:5000"  # Expose port 5000 di host ke port 5000 di container
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:umam2210@postgres:5432/db-todo  

  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"  # Expose port 5432 di container ke port 5432 di host
    environment:
      - POSTGRES_DB=db-todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=umam2210
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volume untuk penyimpanan data persisten

volumes:
  postgres-data:
    driver: local
