# Use the official Python image from the Docker Hub
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirement.txt /app/requirement.txt

# Install the dependenci
RUN pip install -r requirement.txt

# Copy the rest of the application code
COPY . .

# Set environment variables for Flask
ENV FLASK_APP=__init__.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development

# Expose the port that the Flask app runs on
EXPOSE 5000

# Command to run the Flask application
CMD ["flask", "run"]
